### ISSUE TITLE
[suggestion] Separate named params from query params

### ISSUE THREAD

**Issue by fljot** [jeremyruppel/as3-router#2]
Image you have mapped route:

<pre>router.mapRoute("/:page", ...);
router.route("/index?page=foo");

function routeHandler(event:RouterEvent):void
{
    var route:IRoute = event.route;
    trace(route.params("page"));// index
}
</pre>

No way to get query param, therefore I suggest to separate params to named params (those defined via :) and query params (defined via GET ?). I see it as (combined to my comment https://github.com/jeremyruppel/as3-router/issues#issue/1/comment/675820 ):

<pre>
route.namedParams["page"]; // index
route.getNamedParam("page"); // index

route.params["page"]; // foo
route.getParam["page"]; // foo</pre>

Opinion? Do you need help with this?

upd: Oh, instead of accessing params directly, check this API http://www.asual.com/swfaddress/docs/en/as/SWFAddress.html#getParameterNames()

**Comment by jeremyruppel** [comment]
I'm not sure how I feel about over-complicating the API for accessing parameters in 
routes. If you have naming conflicts between route segments and query string parameters, this could indicate a poorly-designed url scheme. 

Also, it is worth noting that Sinatra's API works the same way: named route segments take precedence over query string parameters in the hash. Try running this simple server to test:

```
#!/usr/bin/env ruby -wKU

require 'rubygems'
require 'sinatra'

# with this route, you can hit `/test?page=foo`
# and it will display the query string value
get '/test' do
  "Value of page param is '#{params[ 'page' ]}'."
end

# with any other route matching this pattern,
# the named route segment's value takes precedence
get '/:page' do
  "Value of page param is '#{params[ 'page' ]}'."
end
```

A route of `/test?page=foo` will yield 'foo', while a route of `/index?page=foo` will yield 'index'. I feel that since Sinatra's routing was the inspiration behind the library, the behavior should match as closely as possible.

**Comment by fljot** [comment]
Well, but that's just one extra method. But you really can have a collision on a separate levels of hierarchy (if router is used for deeplinking with SWFAddress) if one guy uses query param and the other guy uses named param with the same name.
If the aim is to duplicate Sinatra's API and behaviour — np, but in general it's like a global variables — u can mess it up.
